import Image from "next/image";
import Link from "next/link";
import { Arrow } from "@/components/Icons";
import { PageHero } from "@/components/PageHero";
import { Reveal } from "@/components/Reveal";

export const metadata = { title: "Over TML", description: "Maak kennis met Tennis Management Limburg, Yannick Quaedvlieg, Bianca Burhenne en adviseur Geert Quaedvlieg." };

const benefits = ["Het werkgeverschap wordt volledig overgenomen.", "Bewaking van de kwaliteit van tennistraining.", "Persoonlijke benadering met managers die voor u klaarstaan.", "Brede advisering over beleid, organisatie en activiteiten.", "Ondersteuning bij open dagen, schooltennis en andere projecten.", "Betrokken en flexibele trainers binnen uw vereniging.", "Facturering van trainingen kan volledig door TML worden overgenomen.", "Ook tenniskampen en tennisreizen voor uw leden."];

export default function AboutPage() {
  return <><PageHero eyebrow="Over TML" title="Persoonlijk in iedere rally." intro="Wij ondersteunen en adviseren verenigingen met mensen die passen, kennis die helpt en aandacht die blijft." image="/images/tml/team-action.webp" />
    <section className="content-section"><div className="wrap editorial-grid"><Reveal><p className="eyebrow">Onze missie</p><h2>De juiste mensen bij elkaar brengen.</h2></Reveal><Reveal className="prose"><p className="lead">Wij zijn Tennis Management Limburg. We ondersteunen tennis- en padelverenigingen met trainingen, activiteiten en advies.</p><p>Dit doen we door de juiste mensen samen te laten trainen onder leiding van een gekwalificeerde en gemotiveerde trainer die bij de vereniging past. Persoonlijke benadering staat bij ons hoog in het vaandel.</p><ul className="feature-list">{benefits.map(b => <li key={b}>{b}</li>)}</ul></Reveal></div></section>
    <section className="content-section white"><div className="wrap"><div className="section-head split"><div><p className="eyebrow">Management & advies</p><h2>Mensen met spelinzicht.</h2></div><p>Sportieve ervaring, organisatorische kennis en korte lijnen komen samen in één betrokken team.</p></div><div className="team-grid"><Person image="/images/tml/yannick-bianca.webp" name="Yannick Quaedvlieg" role="Eigenaar · Manager · Trainer" text="Vanaf de start betrokken bij TML en uitgegroeid tot manager die de organisatie van A tot Z kent. Ervaren clubtrainer, organisator en begeleider van trainers en studenten." /><Person image="/images/tml/yannick-bianca.webp" name="Bianca Burhenne" role="Eigenaar · Manager · Trainer" text="Ervaren clubtrainer en organisator met persoonlijke aandacht voor verenigingen, trainers en leden. Brengt sportieve en financiële kennis samen in de dagelijkse leiding van TML." /><Person image="/images/tml/geert.webp" name="Geert Quaedvlieg" role="Oprichter · Adviseur" text="Geert is oprichter van TML en nog altijd actief als adviseur. Hij was clubtrainer bij grote Limburgse verenigingen, districtstrainer voor de KNLTB en begeleidde nationale jeugdploegen met onder anderen Richard Krajicek, Jan Siemerink en Rogier Wassen. Later werkte hij met Rogier Wassen op het profcircuit." advisor /></div></div></section>
    <section className="cta-band"><div className="wrap"><h2>Samenwerken met TML?</h2><Link href="/contact" className="button button-dark">Maak kennis <Arrow /></Link></div></section></>;
}

function Person({ image, name, role, text, advisor = false }: { image: string; name: string; role: string; text: string; advisor?: boolean }) { return <Reveal className={`person ${advisor ? "advisor" : ""}`}><div className="person-image"><Image src={image} alt={`${name} van Tennis Management Limburg`} fill sizes={advisor ? "(max-width: 680px) 100vw, 50vw" : "(max-width: 980px) 100vw, 50vw"} style={!advisor && name.startsWith("Bianca") ? { objectPosition: "70% top" } : undefined} /></div><div className="person-copy"><p className="eyebrow">{role}</p><h3>{name}</h3><p>{text}</p></div></Reveal>; }
